alias ll='ls -l'
alias la='ls -a'
alias vi='vim'
alias svi='sudo vim'
alias grep='grep --color=auto'
alias install='sudo pacman -S'
alias remove='sudo pacman -Rcn'
alias upgrade='sudo pacman -Syu'
alias findProc='ps -ef | grep '
alias docker='sudo docker '
alias cls='printf "\033c"'
